#!/usr/bin/python

import os

repo_list= ['ops-aaa-utils', 'ops-arpmgrd', 'ops-classifierd', 'ops-cli', 'ops-dhcp-tftp', 'ops-fand', 'ops-hw-config', 'ops-intfd', 'ops-ipapps', 'ops-l2macd', 'ops-lacpd', 'ops-lldpd', 'ops-ntpd', 'ops-portd', 'ops-stpd', 'ops-switchd', 'ops-sysd', 'ops-vland']
os.system('make devenv_init')
cur_dir = os.getcwd()
for repo in repo_list:
    os.system('make devenv_add ' + repo)
    os.chdir(cur_dir + '/src/' + repo)
    os.system('git checkout meraswitch/devel/baikal')
    os.chdir(cur_dir)

